[versions]
agp = "8.3.0"
appcompat = "1.6.1"
material = "1.11.0"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }